AllCops:
  TargetRubyVersion: 2.5.0
  NewCops: enable
  SuggestExtensions: false

Lint/ConstantDefinitionInBlock:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Exclude:
    - lib/ar2dto/dto.rb

Metrics/BlockLength:
  Exclude:
    - lib/ar2dto/dto.rb
    - spec/**/*

Metrics/MethodLength:
  Enabled: true
  Exclude:
   - lib/ar2dto/dto.rb

Naming/PredicateName:
  Exclude:
    - lib/ar2dto/has_dto.rb

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes
