AllCops:
  TargetRubyVersion: 2.5.0
  NewCops: enable
  SuggestExtensions: false

Metrics/MethodLength:
  Enabled: true
  Exclude:
   - lib/ar2dto/base.rb

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Lint/ConstantDefinitionInBlock:
  Enabled: false

Layout/LineLength:
  Max: 120
